### PR TITLE
SRC formatting fixes

### PR DESCRIPTION
**Pull request by SaugataGhose**
Hoping to fix bullet issues by removing leading spaces in md

### CODE REVIEW

**Comment by inducer** [comment]
The leading spaces get removed, see here:

https://github.com/pact-2022/pact-2022.github.io/blob/6f839ff592724d14979ab1b61d5698205fdd12aa/generate.py#L48-L49

So I don't think this'll change anything. The rendered page looks fine to me, FWIW: https://pact22.cs.illinois.edu/src.html

What are you looking to change?

**Comment by inducer** [comment]
(Btw, I use linear history here, so if you use "merge" on your end, you just create a tangle of commits. Use `git pull --rebase` instead.)

**Comment by SaugataGhose** [comment]
There are two things that aren't rendering properly on the current page:
1. The numbered bullets in the first paragraph under "About the SRC"
2. Sub-bullets under both the "Important Dates & Links" and "Extended Abstract Guidelines" sections

Not sure why they aren't. Any ideas?

I can fix up the repo and do a rebase if that helps. I was being lazy and trying to rebase on GitHub Desktop instead of using the command line, and it wasn't syncing updates from upstream (which I'm willing to bet is user error :-) )

**Comment by inducer** [comment]
Ah, got it. FTFY, I think: 196e2d95428076951486aa078ef23f223921b942 Could you check?

- Sub-bullets needs indentation by 4.
- Bulleted lists need a blank line before them.

**Comment by SaugataGhose** [comment]
Ahh that looks good! Sorry - I'm clearly getting rusty with my Markdown... Closing the request now

**Pull request closed without merging**
